#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GanininForumOdevi")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_baslik(tbl_baslik instance);
    partial void Updatetbl_baslik(tbl_baslik instance);
    partial void Deletetbl_baslik(tbl_baslik instance);
    partial void Inserttbl_mesaj(tbl_mesaj instance);
    partial void Updatetbl_mesaj(tbl_mesaj instance);
    partial void Deletetbl_mesaj(tbl_mesaj instance);
    partial void Inserttbl_kategori(tbl_kategori instance);
    partial void Updatetbl_kategori(tbl_kategori instance);
    partial void Deletetbl_kategori(tbl_kategori instance);
    partial void Inserttbl_kullanici(tbl_kullanici instance);
    partial void Updatetbl_kullanici(tbl_kullanici instance);
    partial void Deletetbl_kullanici(tbl_kullanici instance);
    partial void Inserttbl_kullaniciFavoriBasliklari(tbl_kullaniciFavoriBasliklari instance);
    partial void Updatetbl_kullaniciFavoriBasliklari(tbl_kullaniciFavoriBasliklari instance);
    partial void Deletetbl_kullaniciFavoriBasliklari(tbl_kullaniciFavoriBasliklari instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GanininForumOdeviConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_baslik> tbl_basliks
		{
			get
			{
				return this.GetTable<tbl_baslik>();
			}
		}
		
		public System.Data.Linq.Table<tbl_mesaj> tbl_mesajs
		{
			get
			{
				return this.GetTable<tbl_mesaj>();
			}
		}
		
		public System.Data.Linq.Table<tbl_kategori> tbl_kategoris
		{
			get
			{
				return this.GetTable<tbl_kategori>();
			}
		}
		
		public System.Data.Linq.Table<tbl_kullanici> tbl_kullanicis
		{
			get
			{
				return this.GetTable<tbl_kullanici>();
			}
		}
		
		public System.Data.Linq.Table<tbl_kullaniciFavoriBasliklari> tbl_kullaniciFavoriBasliklaris
		{
			get
			{
				return this.GetTable<tbl_kullaniciFavoriBasliklari>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_baslik")]
	public partial class tbl_baslik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Isim;
		
		private System.DateTime _EklenmeTarihi;
		
		private int _KategoriId;
		
		private int _KullaniciId;
		
		private bool _Onay;
		
		private EntitySet<tbl_mesaj> _tbl_mesajs;
		
		private EntitySet<tbl_kullaniciFavoriBasliklari> _tbl_kullaniciFavoriBasliklaris;
		
		private EntityRef<tbl_kategori> _tbl_kategori;
		
		private EntityRef<tbl_kullanici> _tbl_kullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIsimChanging(string value);
    partial void OnIsimChanged();
    partial void OnEklenmeTarihiChanging(System.DateTime value);
    partial void OnEklenmeTarihiChanged();
    partial void OnKategoriIdChanging(int value);
    partial void OnKategoriIdChanged();
    partial void OnKullaniciIdChanging(int value);
    partial void OnKullaniciIdChanged();
    partial void OnOnayChanging(bool value);
    partial void OnOnayChanged();
    #endregion
		
		public tbl_baslik()
		{
			this._tbl_mesajs = new EntitySet<tbl_mesaj>(new Action<tbl_mesaj>(this.attach_tbl_mesajs), new Action<tbl_mesaj>(this.detach_tbl_mesajs));
			this._tbl_kullaniciFavoriBasliklaris = new EntitySet<tbl_kullaniciFavoriBasliklari>(new Action<tbl_kullaniciFavoriBasliklari>(this.attach_tbl_kullaniciFavoriBasliklaris), new Action<tbl_kullaniciFavoriBasliklari>(this.detach_tbl_kullaniciFavoriBasliklaris));
			this._tbl_kategori = default(EntityRef<tbl_kategori>);
			this._tbl_kullanici = default(EntityRef<tbl_kullanici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isim", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Isim
		{
			get
			{
				return this._Isim;
			}
			set
			{
				if ((this._Isim != value))
				{
					this.OnIsimChanging(value);
					this.SendPropertyChanging();
					this._Isim = value;
					this.SendPropertyChanged("Isim");
					this.OnIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklenmeTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime EklenmeTarihi
		{
			get
			{
				return this._EklenmeTarihi;
			}
			set
			{
				if ((this._EklenmeTarihi != value))
				{
					this.OnEklenmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._EklenmeTarihi = value;
					this.SendPropertyChanged("EklenmeTarihi");
					this.OnEklenmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriId", DbType="Int NOT NULL")]
		public int KategoriId
		{
			get
			{
				return this._KategoriId;
			}
			set
			{
				if ((this._KategoriId != value))
				{
					if (this._tbl_kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriIdChanging(value);
					this.SendPropertyChanging();
					this._KategoriId = value;
					this.SendPropertyChanged("KategoriId");
					this.OnKategoriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciId", DbType="Int NOT NULL")]
		public int KullaniciId
		{
			get
			{
				return this._KullaniciId;
			}
			set
			{
				if ((this._KullaniciId != value))
				{
					if (this._tbl_kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKullaniciIdChanging(value);
					this.SendPropertyChanging();
					this._KullaniciId = value;
					this.SendPropertyChanged("KullaniciId");
					this.OnKullaniciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay", DbType="Bit NOT NULL")]
		public bool Onay
		{
			get
			{
				return this._Onay;
			}
			set
			{
				if ((this._Onay != value))
				{
					this.OnOnayChanging(value);
					this.SendPropertyChanging();
					this._Onay = value;
					this.SendPropertyChanged("Onay");
					this.OnOnayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_baslik_tbl_mesaj", Storage="_tbl_mesajs", ThisKey="Id", OtherKey="BaslikId")]
		public EntitySet<tbl_mesaj> tbl_mesajs
		{
			get
			{
				return this._tbl_mesajs;
			}
			set
			{
				this._tbl_mesajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_baslik_tbl_kullaniciFavoriBasliklari", Storage="_tbl_kullaniciFavoriBasliklaris", ThisKey="Id", OtherKey="BaslikId")]
		public EntitySet<tbl_kullaniciFavoriBasliklari> tbl_kullaniciFavoriBasliklaris
		{
			get
			{
				return this._tbl_kullaniciFavoriBasliklaris;
			}
			set
			{
				this._tbl_kullaniciFavoriBasliklaris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kategori_tbl_baslik", Storage="_tbl_kategori", ThisKey="KategoriId", OtherKey="Id", IsForeignKey=true)]
		public tbl_kategori tbl_kategori
		{
			get
			{
				return this._tbl_kategori.Entity;
			}
			set
			{
				tbl_kategori previousValue = this._tbl_kategori.Entity;
				if (((previousValue != value) 
							|| (this._tbl_kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_kategori.Entity = null;
						previousValue.tbl_basliks.Remove(this);
					}
					this._tbl_kategori.Entity = value;
					if ((value != null))
					{
						value.tbl_basliks.Add(this);
						this._KategoriId = value.Id;
					}
					else
					{
						this._KategoriId = default(int);
					}
					this.SendPropertyChanged("tbl_kategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kullanici_tbl_baslik", Storage="_tbl_kullanici", ThisKey="KullaniciId", OtherKey="Id", IsForeignKey=true)]
		public tbl_kullanici tbl_kullanici
		{
			get
			{
				return this._tbl_kullanici.Entity;
			}
			set
			{
				tbl_kullanici previousValue = this._tbl_kullanici.Entity;
				if (((previousValue != value) 
							|| (this._tbl_kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_kullanici.Entity = null;
						previousValue.tbl_basliks.Remove(this);
					}
					this._tbl_kullanici.Entity = value;
					if ((value != null))
					{
						value.tbl_basliks.Add(this);
						this._KullaniciId = value.Id;
					}
					else
					{
						this._KullaniciId = default(int);
					}
					this.SendPropertyChanged("tbl_kullanici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_mesajs(tbl_mesaj entity)
		{
			this.SendPropertyChanging();
			entity.tbl_baslik = this;
		}
		
		private void detach_tbl_mesajs(tbl_mesaj entity)
		{
			this.SendPropertyChanging();
			entity.tbl_baslik = null;
		}
		
		private void attach_tbl_kullaniciFavoriBasliklaris(tbl_kullaniciFavoriBasliklari entity)
		{
			this.SendPropertyChanging();
			entity.tbl_baslik = this;
		}
		
		private void detach_tbl_kullaniciFavoriBasliklaris(tbl_kullaniciFavoriBasliklari entity)
		{
			this.SendPropertyChanging();
			entity.tbl_baslik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_mesaj")]
	public partial class tbl_mesaj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _BaslikId;
		
		private int _KullanıcıId;
		
		private System.DateTime _EklenmeTarihi;
		
		private string _MesajYazısı;
		
		private int _BegeniSayisi;
		
		private int _BegenilmemeSayisi;
		
		private EntityRef<tbl_baslik> _tbl_baslik;
		
		private EntityRef<tbl_kullanici> _tbl_kullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBaslikIdChanging(int value);
    partial void OnBaslikIdChanged();
    partial void OnKullanıcıIdChanging(int value);
    partial void OnKullanıcıIdChanged();
    partial void OnEklenmeTarihiChanging(System.DateTime value);
    partial void OnEklenmeTarihiChanged();
    partial void OnMesajYazısıChanging(string value);
    partial void OnMesajYazısıChanged();
    partial void OnBegeniSayisiChanging(int value);
    partial void OnBegeniSayisiChanged();
    partial void OnBegenilmemeSayisiChanging(int value);
    partial void OnBegenilmemeSayisiChanged();
    #endregion
		
		public tbl_mesaj()
		{
			this._tbl_baslik = default(EntityRef<tbl_baslik>);
			this._tbl_kullanici = default(EntityRef<tbl_kullanici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaslikId", DbType="Int NOT NULL")]
		public int BaslikId
		{
			get
			{
				return this._BaslikId;
			}
			set
			{
				if ((this._BaslikId != value))
				{
					if (this._tbl_baslik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBaslikIdChanging(value);
					this.SendPropertyChanging();
					this._BaslikId = value;
					this.SendPropertyChanged("BaslikId");
					this.OnBaslikIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullanıcıId", DbType="Int NOT NULL")]
		public int KullanıcıId
		{
			get
			{
				return this._KullanıcıId;
			}
			set
			{
				if ((this._KullanıcıId != value))
				{
					if (this._tbl_kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKullanıcıIdChanging(value);
					this.SendPropertyChanging();
					this._KullanıcıId = value;
					this.SendPropertyChanged("KullanıcıId");
					this.OnKullanıcıIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EklenmeTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime EklenmeTarihi
		{
			get
			{
				return this._EklenmeTarihi;
			}
			set
			{
				if ((this._EklenmeTarihi != value))
				{
					this.OnEklenmeTarihiChanging(value);
					this.SendPropertyChanging();
					this._EklenmeTarihi = value;
					this.SendPropertyChanged("EklenmeTarihi");
					this.OnEklenmeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesajYazısı", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string MesajYazısı
		{
			get
			{
				return this._MesajYazısı;
			}
			set
			{
				if ((this._MesajYazısı != value))
				{
					this.OnMesajYazısıChanging(value);
					this.SendPropertyChanging();
					this._MesajYazısı = value;
					this.SendPropertyChanged("MesajYazısı");
					this.OnMesajYazısıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BegeniSayisi", DbType="Int NOT NULL")]
		public int BegeniSayisi
		{
			get
			{
				return this._BegeniSayisi;
			}
			set
			{
				if ((this._BegeniSayisi != value))
				{
					this.OnBegeniSayisiChanging(value);
					this.SendPropertyChanging();
					this._BegeniSayisi = value;
					this.SendPropertyChanged("BegeniSayisi");
					this.OnBegeniSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BegenilmemeSayisi", DbType="Int NOT NULL")]
		public int BegenilmemeSayisi
		{
			get
			{
				return this._BegenilmemeSayisi;
			}
			set
			{
				if ((this._BegenilmemeSayisi != value))
				{
					this.OnBegenilmemeSayisiChanging(value);
					this.SendPropertyChanging();
					this._BegenilmemeSayisi = value;
					this.SendPropertyChanged("BegenilmemeSayisi");
					this.OnBegenilmemeSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_baslik_tbl_mesaj", Storage="_tbl_baslik", ThisKey="BaslikId", OtherKey="Id", IsForeignKey=true)]
		public tbl_baslik tbl_baslik
		{
			get
			{
				return this._tbl_baslik.Entity;
			}
			set
			{
				tbl_baslik previousValue = this._tbl_baslik.Entity;
				if (((previousValue != value) 
							|| (this._tbl_baslik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_baslik.Entity = null;
						previousValue.tbl_mesajs.Remove(this);
					}
					this._tbl_baslik.Entity = value;
					if ((value != null))
					{
						value.tbl_mesajs.Add(this);
						this._BaslikId = value.Id;
					}
					else
					{
						this._BaslikId = default(int);
					}
					this.SendPropertyChanged("tbl_baslik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kullanici_tbl_mesaj", Storage="_tbl_kullanici", ThisKey="KullanıcıId", OtherKey="Id", IsForeignKey=true)]
		public tbl_kullanici tbl_kullanici
		{
			get
			{
				return this._tbl_kullanici.Entity;
			}
			set
			{
				tbl_kullanici previousValue = this._tbl_kullanici.Entity;
				if (((previousValue != value) 
							|| (this._tbl_kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_kullanici.Entity = null;
						previousValue.tbl_mesajs.Remove(this);
					}
					this._tbl_kullanici.Entity = value;
					if ((value != null))
					{
						value.tbl_mesajs.Add(this);
						this._KullanıcıId = value.Id;
					}
					else
					{
						this._KullanıcıId = default(int);
					}
					this.SendPropertyChanged("tbl_kullanici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_kategori")]
	public partial class tbl_kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Isim;
		
		private bool _Aktif;
		
		private EntitySet<tbl_baslik> _tbl_basliks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIsimChanging(string value);
    partial void OnIsimChanged();
    partial void OnAktifChanging(bool value);
    partial void OnAktifChanged();
    #endregion
		
		public tbl_kategori()
		{
			this._tbl_basliks = new EntitySet<tbl_baslik>(new Action<tbl_baslik>(this.attach_tbl_basliks), new Action<tbl_baslik>(this.detach_tbl_basliks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isim", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Isim
		{
			get
			{
				return this._Isim;
			}
			set
			{
				if ((this._Isim != value))
				{
					this.OnIsimChanging(value);
					this.SendPropertyChanging();
					this._Isim = value;
					this.SendPropertyChanged("Isim");
					this.OnIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aktif", DbType="Bit NOT NULL")]
		public bool Aktif
		{
			get
			{
				return this._Aktif;
			}
			set
			{
				if ((this._Aktif != value))
				{
					this.OnAktifChanging(value);
					this.SendPropertyChanging();
					this._Aktif = value;
					this.SendPropertyChanged("Aktif");
					this.OnAktifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kategori_tbl_baslik", Storage="_tbl_basliks", ThisKey="Id", OtherKey="KategoriId")]
		public EntitySet<tbl_baslik> tbl_basliks
		{
			get
			{
				return this._tbl_basliks;
			}
			set
			{
				this._tbl_basliks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_basliks(tbl_baslik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kategori = this;
		}
		
		private void detach_tbl_basliks(tbl_baslik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_kullanici")]
	public partial class tbl_kullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Isim;
		
		private string _Soyisim;
		
		private string _Eposta;
		
		private string _Sifre;
		
		private string _FakulteIsim;
		
		private string _Hakkinda;
		
		private System.Nullable<System.DateTime> _DogumTarihi;
		
		private EntitySet<tbl_baslik> _tbl_basliks;
		
		private EntitySet<tbl_mesaj> _tbl_mesajs;
		
		private EntitySet<tbl_kullaniciFavoriBasliklari> _tbl_kullaniciFavoriBasliklaris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIsimChanging(string value);
    partial void OnIsimChanged();
    partial void OnSoyisimChanging(string value);
    partial void OnSoyisimChanged();
    partial void OnEpostaChanging(string value);
    partial void OnEpostaChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnFakulteIsimChanging(string value);
    partial void OnFakulteIsimChanged();
    partial void OnHakkindaChanging(string value);
    partial void OnHakkindaChanged();
    partial void OnDogumTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnDogumTarihiChanged();
    #endregion
		
		public tbl_kullanici()
		{
			this._tbl_basliks = new EntitySet<tbl_baslik>(new Action<tbl_baslik>(this.attach_tbl_basliks), new Action<tbl_baslik>(this.detach_tbl_basliks));
			this._tbl_mesajs = new EntitySet<tbl_mesaj>(new Action<tbl_mesaj>(this.attach_tbl_mesajs), new Action<tbl_mesaj>(this.detach_tbl_mesajs));
			this._tbl_kullaniciFavoriBasliklaris = new EntitySet<tbl_kullaniciFavoriBasliklari>(new Action<tbl_kullaniciFavoriBasliklari>(this.attach_tbl_kullaniciFavoriBasliklaris), new Action<tbl_kullaniciFavoriBasliklari>(this.detach_tbl_kullaniciFavoriBasliklaris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Isim
		{
			get
			{
				return this._Isim;
			}
			set
			{
				if ((this._Isim != value))
				{
					this.OnIsimChanging(value);
					this.SendPropertyChanging();
					this._Isim = value;
					this.SendPropertyChanged("Isim");
					this.OnIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyisim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyisim
		{
			get
			{
				return this._Soyisim;
			}
			set
			{
				if ((this._Soyisim != value))
				{
					this.OnSoyisimChanging(value);
					this.SendPropertyChanging();
					this._Soyisim = value;
					this.SendPropertyChanged("Soyisim");
					this.OnSoyisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eposta", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Eposta
		{
			get
			{
				return this._Eposta;
			}
			set
			{
				if ((this._Eposta != value))
				{
					this.OnEpostaChanging(value);
					this.SendPropertyChanging();
					this._Eposta = value;
					this.SendPropertyChanged("Eposta");
					this.OnEpostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FakulteIsim", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FakulteIsim
		{
			get
			{
				return this._FakulteIsim;
			}
			set
			{
				if ((this._FakulteIsim != value))
				{
					this.OnFakulteIsimChanging(value);
					this.SendPropertyChanging();
					this._FakulteIsim = value;
					this.SendPropertyChanged("FakulteIsim");
					this.OnFakulteIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hakkinda", DbType="NVarChar(500)")]
		public string Hakkinda
		{
			get
			{
				return this._Hakkinda;
			}
			set
			{
				if ((this._Hakkinda != value))
				{
					this.OnHakkindaChanging(value);
					this.SendPropertyChanging();
					this._Hakkinda = value;
					this.SendPropertyChanged("Hakkinda");
					this.OnHakkindaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> DogumTarihi
		{
			get
			{
				return this._DogumTarihi;
			}
			set
			{
				if ((this._DogumTarihi != value))
				{
					this.OnDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._DogumTarihi = value;
					this.SendPropertyChanged("DogumTarihi");
					this.OnDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kullanici_tbl_baslik", Storage="_tbl_basliks", ThisKey="Id", OtherKey="KullaniciId")]
		public EntitySet<tbl_baslik> tbl_basliks
		{
			get
			{
				return this._tbl_basliks;
			}
			set
			{
				this._tbl_basliks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kullanici_tbl_mesaj", Storage="_tbl_mesajs", ThisKey="Id", OtherKey="KullanıcıId")]
		public EntitySet<tbl_mesaj> tbl_mesajs
		{
			get
			{
				return this._tbl_mesajs;
			}
			set
			{
				this._tbl_mesajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kullanici_tbl_kullaniciFavoriBasliklari", Storage="_tbl_kullaniciFavoriBasliklaris", ThisKey="Id", OtherKey="KullaniciId")]
		public EntitySet<tbl_kullaniciFavoriBasliklari> tbl_kullaniciFavoriBasliklaris
		{
			get
			{
				return this._tbl_kullaniciFavoriBasliklaris;
			}
			set
			{
				this._tbl_kullaniciFavoriBasliklaris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_basliks(tbl_baslik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kullanici = this;
		}
		
		private void detach_tbl_basliks(tbl_baslik entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kullanici = null;
		}
		
		private void attach_tbl_mesajs(tbl_mesaj entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kullanici = this;
		}
		
		private void detach_tbl_mesajs(tbl_mesaj entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kullanici = null;
		}
		
		private void attach_tbl_kullaniciFavoriBasliklaris(tbl_kullaniciFavoriBasliklari entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kullanici = this;
		}
		
		private void detach_tbl_kullaniciFavoriBasliklaris(tbl_kullaniciFavoriBasliklari entity)
		{
			this.SendPropertyChanging();
			entity.tbl_kullanici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_kullaniciFavoriBasliklari")]
	public partial class tbl_kullaniciFavoriBasliklari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _KullaniciId;
		
		private int _BaslikId;
		
		private EntityRef<tbl_baslik> _tbl_baslik;
		
		private EntityRef<tbl_kullanici> _tbl_kullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKullaniciIdChanging(int value);
    partial void OnKullaniciIdChanged();
    partial void OnBaslikIdChanging(int value);
    partial void OnBaslikIdChanged();
    #endregion
		
		public tbl_kullaniciFavoriBasliklari()
		{
			this._tbl_baslik = default(EntityRef<tbl_baslik>);
			this._tbl_kullanici = default(EntityRef<tbl_kullanici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciId", DbType="Int NOT NULL")]
		public int KullaniciId
		{
			get
			{
				return this._KullaniciId;
			}
			set
			{
				if ((this._KullaniciId != value))
				{
					if (this._tbl_kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKullaniciIdChanging(value);
					this.SendPropertyChanging();
					this._KullaniciId = value;
					this.SendPropertyChanged("KullaniciId");
					this.OnKullaniciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaslikId", DbType="Int NOT NULL")]
		public int BaslikId
		{
			get
			{
				return this._BaslikId;
			}
			set
			{
				if ((this._BaslikId != value))
				{
					if (this._tbl_baslik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBaslikIdChanging(value);
					this.SendPropertyChanging();
					this._BaslikId = value;
					this.SendPropertyChanged("BaslikId");
					this.OnBaslikIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_baslik_tbl_kullaniciFavoriBasliklari", Storage="_tbl_baslik", ThisKey="BaslikId", OtherKey="Id", IsForeignKey=true)]
		public tbl_baslik tbl_baslik
		{
			get
			{
				return this._tbl_baslik.Entity;
			}
			set
			{
				tbl_baslik previousValue = this._tbl_baslik.Entity;
				if (((previousValue != value) 
							|| (this._tbl_baslik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_baslik.Entity = null;
						previousValue.tbl_kullaniciFavoriBasliklaris.Remove(this);
					}
					this._tbl_baslik.Entity = value;
					if ((value != null))
					{
						value.tbl_kullaniciFavoriBasliklaris.Add(this);
						this._BaslikId = value.Id;
					}
					else
					{
						this._BaslikId = default(int);
					}
					this.SendPropertyChanged("tbl_baslik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_kullanici_tbl_kullaniciFavoriBasliklari", Storage="_tbl_kullanici", ThisKey="KullaniciId", OtherKey="Id", IsForeignKey=true)]
		public tbl_kullanici tbl_kullanici
		{
			get
			{
				return this._tbl_kullanici.Entity;
			}
			set
			{
				tbl_kullanici previousValue = this._tbl_kullanici.Entity;
				if (((previousValue != value) 
							|| (this._tbl_kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_kullanici.Entity = null;
						previousValue.tbl_kullaniciFavoriBasliklaris.Remove(this);
					}
					this._tbl_kullanici.Entity = value;
					if ((value != null))
					{
						value.tbl_kullaniciFavoriBasliklaris.Add(this);
						this._KullaniciId = value.Id;
					}
					else
					{
						this._KullaniciId = default(int);
					}
					this.SendPropertyChanged("tbl_kullanici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
